/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'name' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'stock' : IDL.Nat,
  'updated' : Time,
  'category' : IDL.Text,
  'costPrice' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Report = IDL.Record({
  'totalCost' : IDL.Float64,
  'totalProfit' : IDL.Float64,
  'topProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalRevenue' : IDL.Float64,
  'transactionCount' : IDL.Nat,
});
export const TransactionItem = IDL.Record({
  'sellingPrice' : IDL.Float64,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'costPrice' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'user' : IDL.Principal,
  'totalCost' : IDL.Float64,
  'totalProfit' : IDL.Float64,
  'timestamp' : Time,
  'items' : IDL.Vec(TransactionItem),
  'totalRevenue' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReport' : IDL.Func([], [Report], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordTransaction' : IDL.Func([IDL.Vec(TransactionItem)], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'name' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'stock' : IDL.Nat,
    'updated' : Time,
    'category' : IDL.Text,
    'costPrice' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Report = IDL.Record({
    'totalCost' : IDL.Float64,
    'totalProfit' : IDL.Float64,
    'topProducts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalRevenue' : IDL.Float64,
    'transactionCount' : IDL.Nat,
  });
  const TransactionItem = IDL.Record({
    'sellingPrice' : IDL.Float64,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'costPrice' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'user' : IDL.Principal,
    'totalCost' : IDL.Float64,
    'totalProfit' : IDL.Float64,
    'timestamp' : Time,
    'items' : IDL.Vec(TransactionItem),
    'totalRevenue' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReport' : IDL.Func([], [Report], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordTransaction' : IDL.Func([IDL.Vec(TransactionItem)], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };